### PR TITLE
Change exception handling, change class name

### PR DESCRIPTION
**Pull request by muandrew**
Let users of the library catch and handle exception themselves instead of bailing.
Let cli catch and exit 1 to signify error
Change class name to be capitalized to make distinct from modules and variables

### CODE REVIEW

**Comment by muandrew** [comment]
Thanks for reviewing the last PR so quickly!

If I find anything that could use improvement I'll be back to make more PRs.

**Comment by muandrew** [comment]
force pushed to update readme

**Comment by krnick** [comment]
Awesome! Thank you for the great work, I will move on updating to PyPi package.

**Comment by muandrew** [comment]
Thanks again for the review!

**Pull request merged**
