### PR TITLE
add sunzip-cli to be used as a command line interface tool

### PR DESCRIPTION
**Pull request by muandrew**
I don't know how you would like your PRs (Pull Requests) to be structured. I can take each commit and make them a stand alone PR or you can take this one.

* `remove .DS_Store` is pretty simple just updating `.gitignore`.
* `migrate to pythong-packaging...` is pretty straightforward also. I have also avoided pulling in any dependencies
* `[cli] add arguments that ...` probably requires more review.
  * I tried to make the argument name as close to your documentation as possible and give it what I think is a simple shorthand.
  * I decided to use two character shorthands because I would like to eventually add back some commands that would appear in `man unzip` which may collide if I used some of the one character ones.
  * The names in your documentation do not match the property names you have for the class `sunzip` I would recommend consolidating that. One example of this is `threshold` vs `compression-ratio`.

### CODE REVIEW

**Comment by muandrew** [comment]
I plan on adding two more changes.
1. add an output directory option
2. add a --silent or --verbose flag.
  * right now your library outputs `All rules have checked completely. Start to unzipping.`
  * I will either add a `--silent` flag where the default behavior is to print log messages or
    a `--verbose` flag where the default behavior is to not print log messages. Let me
    know what you prefer.

**Comment by krnick** [comment]
@muandrew 

Thank you very much for your help and the pull request. It looks good to me. Once you have done these changes, I will merge this and then update it to PyPi package.

> I plan on adding two more changes.
> 
> 1. add an output directory option
> 2. add a --silent or --verbose flag.
> 
> * right now your library outputs `All rules have checked completely. Start to unzipping.`
> * I will either add a `--silent` flag where the default behavior is to print log messages or
>   a `--verbose` flag where the default behavior is to not print log messages. Let me
>   know what you prefer.

--verbose seems better 😄 

Thank you very much for making sunzip better！

**Comment by muandrew** [comment]
The changes are ready for review. After this PR I will open another change, see muandrew:amu_exception. I have made deeper changes to the class's expected behavior so I didn't want to bundle it up into this PR. I would also like to change your class name `sunzip` to `Sunzip` in a separate change if you don't mind.

Thanks!

**Comment by krnick** [comment]
Thanks for this Pull Request, nice work. LGTM

> The changes are ready for review. After this PR I will open another change, see muandrew:amu_exception. I have made deeper changes to the class's expected behavior so I didn't want to bundle it up into this PR. I would also like to change your class name `sunzip` to `Sunzip` in a separate change if you don't mind.
> 
> Thanks!

sounds great! Thanks

**Pull request merged**
